export const avatarAssets: Record<string, number> = {
  'ace_of_spades':   require('./ace_of_spades.jpg'),
  '2_of_spades':     require('./2_of_spades.jpg'),
  '3_of_spades':     require('./3_of_spades.jpg'),
  '4_of_spades':     require('./4_of_spades.jpg'),
  '5_of_spades':     require('./5_of_spades.jpg'),
  '6_of_spades':     require('./6_of_spades.jpg'),
  '7_of_spades':     require('./7_of_spades.jpg'),
  '8_of_spades':     require('./8_of_spades.jpg'),
  '9_of_spades':     require('./9_of_spades.jpg'),
  '10_of_spades':    require('./10_of_spades.jpg'),
  'jack_of_spades':  require('./jack_of_spades.jpg'),
  'queen_of_spades': require('./queen_of_spades.jpg'),
  'king_of_spades':  require('./king_of_spades.jpg'),

  'ace_of_diamonds':   require('./ace_of_diamonds.jpg'),
  '2_of_diamonds':     require('./2_of_diamonds.jpg'),
  '3_of_diamonds':     require('./3_of_diamonds.jpg'),
  '4_of_diamonds':     require('./4_of_diamonds.jpg'),
  '5_of_diamonds':     require('./5_of_diamonds.jpg'),
  '6_of_diamonds':     require('./6_of_diamonds.jpg'),
  '7_of_diamonds':     require('./7_of_diamonds.jpg'),
  '8_of_diamonds':     require('./8_of_diamonds.jpg'),
  '9_of_diamonds':     require('./9_of_diamonds.jpg'),
  '10_of_diamonds':    require('./10_of_diamonds.jpg'),
  'jack_of_diamonds':  require('./jack_of_diamonds.jpg'),
  'queen_of_diamonds': require('./queen_of_diamonds.jpg'),
  'king_of_diamonds':  require('./king_of_diamonds.jpg'),

  'ace_of_clubs':   require('./ace_of_clubs.jpg'),
  '2_of_clubs':     require('./2_of_clubs.jpg'),
  '3_of_clubs':     require('./3_of_clubs.jpg'),
  '4_of_clubs':     require('./4_of_clubs.jpg'),
  '5_of_clubs':     require('./5_of_clubs.jpg'),
  '6_of_clubs':     require('./6_of_clubs.jpg'),
  '7_of_clubs':     require('./7_of_clubs.jpg'),
  '8_of_clubs':     require('./8_of_clubs.jpg'),
  '9_of_clubs':     require('./9_of_clubs.jpg'),
  '10_of_clubs':    require('./10_of_clubs.jpg'),
  'jack_of_clubs':  require('./jack_of_clubs.jpg'),
  'queen_of_clubs': require('./queen_of_clubs.jpg'),
  'king_of_clubs':  require('./king_of_clubs.jpg'),

  'ace_of_hearts':   require('./ace_of_hearts.jpg'),
  '2_of_hearts':     require('./2_of_hearts.jpg'),
  '3_of_hearts':     require('./3_of_hearts.jpg'),
  '4_of_hearts':     require('./4_of_hearts.jpg'),
  '5_of_hearts':     require('./5_of_hearts.jpg'),
  '6_of_hearts':     require('./6_of_hearts.jpg'),
  '7_of_hearts':     require('./7_of_hearts.jpg'),
  '8_of_hearts':     require('./8_of_hearts.jpg'),
  '9_of_hearts':     require('./9_of_hearts.jpg'),
  '10_of_hearts':    require('./10_of_hearts.jpg'),
  'jack_of_hearts':  require('./jack_of_hearts.jpg'),
  'queen_of_hearts': require('./queen_of_hearts.jpg'),
  'king_of_hearts':  require('./king_of_hearts.jpg'),
};
