const spellImages: Record<string, any> = {
  "Acid Arrow"                   : require('./acid_arrow.jpg'),
  "Acid Splash"                  : require('./acid_splash.jpg'),
  "Aid"                          : require('./aid.jpg'),
  "Alarm"                        : require('./alarm.jpg'),
  "Alter Self"                   : require('./alter_self.jpg'),
  "Animal Friendship"            : require('./animal_friendship.jpg'),
  "Animal Messenger"             : require('./animal_messenger.jpg'),
  "Animal Shapes"                : require('./animal_shapes.jpg'),
  "Animate Dead"                 : require('./animate_dead.jpg'),
  "Animate Objects"              : require('./animate_objects.jpg'),
  "Antilife Shell"               : require('./antilife_shell.jpg'),
  "Antimagic Field"              : require('./antimagic_field.jpg'),
  "Antipathy/Sympathy"           : require('./antipathy_sympathy.jpg'),
  "Arcane Eye"                   : require('./arcane_eye.jpg'),
  "Arcane Hand"                  : require('./arcane_hand.jpg'),
  "Arcane Lock"                  : require('./arcane_lock.jpg'),
  "Arcane Sword"                 : require('./arcane_sword.jpg'),
  "Arcanist's Magic Aura"        : require('./arcanists_magic_aura.jpg'),
  "Astral Projection"            : require('./astral_projection.jpg'),
  "Augury"                       : require('./augury.jpg'),
  "Awaken"                       : require('./awaken.jpg'),
  "Bane"                         : require('./bane.jpg'),
  "Banishment"                   : require('./banishment.jpg'),
  "Barkskin"                     : require('./barkskin.jpg'),
  "Beacon of Hope"               : require('./beacon_of_hope.jpg'),
  "Bestow Curse"                 : require('./bestow_curse.jpg'),
  "Black Tentacles"              : require('./black_tentacles.jpg'),
  "Blade Barrier"                : require('./blade_barrier.jpg'),
  "Bless"                        : require('./bless.jpg'),
  "Blight"                       : require('./blight.jpg'),
  "Blindness/Deafness"           : require('./blindness_deafness.jpg'),
  "Blink"                        : require('./blink.jpg'),
  "Blur"                         : require('./blur.jpg'),
  "Burning Hands"                : require('./burning_hands.jpg'),
  "Call Lightning"               : require('./call_lightning.jpg'),
  "Calm Emotions"                : require('./calm_emotions.jpg'),
  "Chain Lightning"              : require('./chain_lightning.jpg'),
  "Charm Person"                 : require('./charm_person.jpg'),
  "Chill Touch"                  : require('./chill_touch.jpg'),
  "Circle of Death"              : require('./circle_of_death.jpg'),
  "Clairvoyance"                 : require('./clairvoyance.jpg'),
  "Clone"                        : require('./clone.jpg'),
  "Cloudkill"                    : require('./cloudkill.jpg'),
  "Color Spray"                  : require('./color_spray.jpg'),
  "Command"                      : require('./command.jpg'),
  "Commune"                      : require('./commune.jpg'),
  "Commune With Nature"          : require('./commune_with_nature.jpg'),
  "Comprehend Languages"         : require('./comprehend_languages.jpg'),
  "Compulsion"                   : require('./compulsion.jpg'),
  "Cone of Cold"                 : require('./cone_of_cold.jpg'),
  "Confusion"                    : require('./confusion.jpg'),
  "Conjure Animals"              : require('./conjure_animals.jpg'),
  "Conjure Celestial"            : require('./conjure_celestial.jpg'),
  "Conjure Elemental"            : require('./conjure_elemental.jpg'),
  "Conjure Fey"                  : require('./conjure_fey.jpg'),
  "Conjure Minor Elementals"     : require('./conjure_minor_elementals.jpg'),
  "Conjure Woodland Beings"      : require('./conjure_woodland_beings.jpg'),
  "Contact Other Plane"          : require('./contact_other_plane.jpg'),
  "Contagion"                    : require('./contagion.jpg'),
  "Contingency"                  : require('./contingency.jpg'),
  "Continual Flame"              : require('./continual_flame.jpg'),
  "Control Water"                : require('./control_water.jpg'),
  "Control Weather"              : require('./control_weather.jpg'),
  "Counterspell"                 : require('./counterspell.jpg'),
  "Create Food and Water"        : require('./create_food_and_water.jpg'),
  "Create Undead"                : require('./create_undead.jpg'),
  "Create or Destroy Water"      : require('./create_or_destroy_water.jpg'),
  "Creation"                     : require('./creation.jpg'),
  "Cure Wounds"                  : require('./cure_wounds.jpg'),
  "Dancing Lights"               : require('./dancing_lights.jpg'),
  "Darkness"                     : require('./darkness.jpg'),
  "Darkvision"                   : require('./darkvision.jpg'),
  "Daylight"                     : require('./daylight.jpg'),
  "Death Ward"                   : require('./death_ward.jpg'),
  "Delayed Blast Fireball"       : require('./delayed_blast_fireball.jpg'),
  "Demiplane"                    : require('./demiplane.jpg'),
  "Detect Evil and Good"         : require('./detect_evil_and_good.jpg'),
  "Detect Magic"                 : require('./detect_magic.jpg'),
  "Detect Poison and Disease"    : require('./detect_poison_and_disease.jpg'),
  "Detect Thoughts"              : require('./detect_thoughts.jpg'),
  "Dimension Door"               : require('./dimension_door.jpg'),
  "Disguise Self"                : require('./disguise_self.jpg'),
  "Disintegrate"                 : require('./disintegrate.jpg'),
  "Dispel Evil and Good"         : require('./dispel_evil_and_good.jpg'),
  "Dispel Magic"                 : require('./dispel_magic.jpg'),
  "Divination"                   : require('./divination.jpg'),
  "Divine Favor"                 : require('./divine_favor.jpg'),
  "Divine Word"                  : require('./divine_word.jpg'),
  "Dominate Beast"               : require('./dominate_beast.jpg'),
  "Dominate Monster"             : require('./dominate_monster.jpg'),
  "Dominate Person"              : require('./dominate_person.jpg'),
  "Dream"                        : require('./dream.jpg'),
  "Druidcraft"                   : require('./druidcraft.jpg'),
  "Earthquake"                   : require('./earthquake.jpg'),
  "Eldritch Blast"               : require('./eldritch_blast.jpg'),
  "Enhance Ability"              : require('./enhance_ability.jpg'),
  "Enlarge/Reduce"               : require('./enlarge_reduce.jpg'),
  "Entangle"                     : require('./entangle.jpg'),
  "Enthrall"                     : require('./enthrall.jpg'),
  "Etherealness"                 : require('./etherealness.jpg'),
  "Expeditious Retreat"          : require('./expeditious_retreat.jpg'),
  "Eyebite"                      : require('./eyebite.jpg'),
  "Fabricate"                    : require('./fabricate.jpg'),
  "Faerie Fire"                  : require('./faerie_fire.jpg'),
  "Faithful Hound"               : require('./faithful_hound.jpg'),
  "False Life"                   : require('./false_life.jpg'),
  "Fear"                         : require('./fear.jpg'),
  "Feather Fall"                 : require('./feather_fall.jpg'),
  "Feeblemind"                   : require('./feeblemind.jpg'),
  "Find Familiar"                : require('./find_familiar.jpg'),
  "Find Steed"                   : require('./find_steed.jpg'),
  "Find Traps"                   : require('./find_traps.jpg'),
  "Find the Path"                : require('./find_the_path.jpg'),
  "Finger of Death"              : require('./finger_of_death.jpg'),
  "Fire Bolt"                    : require('./fire_bolt.jpg'),
  "Fire Shield"                  : require('./fire_shield.jpg'),
  "Fire Storm"                   : require('./fire_storm.jpg'),
  "Fireball"                     : require('./fireball.jpg'),
  "Flame Blade"                  : require('./flame_blade.jpg'),
  "Flame Strike"                 : require('./flame_strike.jpg'),
  "Flaming Sphere"               : require('./flaming_sphere.jpg'),
  "Flesh to Stone"               : require('./flesh_to_stone.jpg'),
  "Floating Disk"                : require('./floating_disk.jpg'),
  "Fly"                          : require('./fly.jpg'),
  "Fog Cloud"                    : require('./fog_cloud.jpg'),
  "Forbiddance"                  : require('./forbiddance.jpg'),
  "Forcecage"                    : require('./forcecage.jpg'),
  "Foresight"                    : require('./foresight.jpg'),
  "Freedom of Movement"          : require('./freedom_of_movement.jpg'),
  "Freezing Sphere"              : require('./freezing_sphere.jpg'),
  "Gaseous Form"                 : require('./gaseous_form.jpg'),
  "Gate"                         : require('./gate.jpg'),
  "Geas"                         : require('./geas.jpg'),
  "Gentle Repose"                : require('./gentle_repose.jpg'),
  "Giant Insect"                 : require('./giant_insect.jpg'),
  "Glibness"                     : require('./glibness.jpg'),
  "Globe of Invulnerability"     : require('./globe_of_invulnerability.jpg'),
  "Glyph of Warding"             : require('./glyph_of_warding.jpg'),
  "Goodberry"                    : require('./goodberry.jpg'),
  "Grease"                       : require('./grease.jpg'),
  "Greater Invisibility"         : require('./greater_invisibility.jpg'),
  "Greater Restoration"          : require('./greater_restoration.jpg'),
  "Guardian of Faith"            : require('./guardian_of_faith.jpg'),
  "Guards and Wards"             : require('./guards_and_wards.jpg'),
  "Guidance"                     : require('./guidance.jpg'),
  "Guiding Bolt"                 : require('./guiding_bolt.jpg'),
  "Gust of Wind"                 : require('./gust_of_wind.jpg'),
  "Hallow"                       : require('./hallow.jpg'),
  "Hallucinatory Terrain"        : require('./hallucinatory_terrain.jpg'),
  "Harm"                         : require('./harm.jpg'),
  "Haste"                        : require('./haste.jpg'),
  "Heal"                         : require('./heal.jpg'),
  "Healing Word"                 : require('./healing_word.jpg'),
  "Heat Metal"                   : require('./heat_metal.jpg'),
  "Hellish Rebuke"               : require('./hellish_rebuke.jpg'),
  "Heroes' Feast"                : require('./heroes_feast.jpg'),
  "Heroism"                      : require('./heroism.jpg'),
  "Hideous Laughter"             : require('./hideous_laughter.jpg'),
  "Hold Monster"                 : require('./hold_monster.jpg'),
  "Hold Person"                  : require('./hold_person.jpg'),
  "Holy Aura"                    : require('./holy_aura.jpg'),
  "Hunter's Mark"                : require('./hunters_mark.jpg'),
  "Hypnotic Pattern"             : require('./hypnotic_pattern.jpg'),
  "Ice Storm"                    : require('./ice_storm.jpg'),
  "Identify"                     : require('./identify.jpg'),
  "Illusory Script"              : require('./illusory_script.jpg'),
  "Imprisonment"                 : require('./imprisonment.jpg'),
  "Incendiary Cloud"             : require('./incendiary_cloud.jpg'),
  "Inflict Wounds"               : require('./inflict_wounds.jpg'),
  "Insect Plague"                : require('./insect_plague.jpg'),
  "Instant Summons"              : require('./instant_summons.jpg'),
  "Invisibility"                 : require('./invisibility.jpg'),
  "Irresistible Dance"           : require('./irresistible_dance.jpg'),
  "Jump"                         : require('./jump.jpg'),
  "Knock"                        : require('./knock.jpg'),
  "Legend Lore"                  : require('./legend_lore.jpg'),
  "Lesser Restoration"           : require('./lesser_restoration.jpg'),
  "Levitate"                     : require('./levitate.jpg'),
  "Light"                        : require('./light.jpg'),
  "Lightning Bolt"               : require('./lightning_bolt.jpg'),
  "Locate Animals or Plants"     : require('./locate_animals_or_plants.jpg'),
  "Locate Creature"              : require('./locate_creature.jpg'),
  "Locate Object"                : require('./locate_object.jpg'),
  "Longstrider"                  : require('./longstrider.jpg'),
  "Mage Armor"                   : require('./mage_armor.jpg'),
  "Mage Hand"                    : require('./mage_hand.jpg'),
  "Magic Circle"                 : require('./magic_circle.jpg'),
  "Magic Jar"                    : require('./magic_jar.jpg'),
  "Magic Missile"                : require('./magic_missile.jpg'),
  "Magic Mouth"                  : require('./magic_mouth.jpg'),
  "Magic Weapon"                 : require('./magic_weapon.jpg'),
  "Magnificent Mansion"          : require('./magnificent_mansion.jpg'),
  "Major Image"                  : require('./major_image.jpg'),
  "Mass Cure Wounds"             : require('./mass_cure_wounds.jpg'),
  "Mass Heal"                    : require('./mass_heal.jpg'),
  "Mass Healing Word"            : require('./mass_healing_word.jpg'),
  "Mass Suggestion"              : require('./mass_suggestion.jpg'),
  "Maze"                         : require('./maze.jpg'),
  "Meld Into Stone"              : require('./meld_into_stone.jpg'),
  "Mending"                      : require('./mending.jpg'),
  "Message"                      : require('./message.jpg'),
  "Meteor Swarm"                 : require('./meteor_swarm.jpg'),
  "Mind Blank"                   : require('./mind_blank.jpg'),
  "Minor Illusion"               : require('./minor_illusion.jpg'),
  "Mirage Arcane"                : require('./mirage_arcane.jpg'),
  "Mirror Image"                 : require('./mirror_image.jpg'),
  "Mislead"                      : require('./mislead.jpg'),
  "Misty Step"                   : require('./misty_step.jpg'),
  "Modify Memory"                : require('./modify_memory.jpg'),
  "Moonbeam"                     : require('./moonbeam.jpg'),
  "Move Earth"                   : require('./move_earth.jpg'),
  "Nondetection"                 : require('./nondetection.jpg'),
  "Pass Without Trace"           : require('./pass_without_trace.jpg'),
  "Passwall"                     : require('./passwall.jpg'),
  "Phantasmal Killer"            : require('./phantasmal_killer.jpg'),
  "Phantom Steed"                : require('./phantom_steed.jpg'),
  "Planar Ally"                  : require('./planar_ally.jpg'),
  "Planar Binding"               : require('./planar_binding.jpg'),
  "Plane Shift"                  : require('./plane_shift.jpg'),
  "Plant Growth"                 : require('./plant_growth.jpg'),
  "Poison Spray"                 : require('./poison_spray.jpg'),
  "Polymorph"                    : require('./polymorph.jpg'),
  "Power Word Kill"              : require('./power_word_kill.jpg'),
  "Power Word Stun"              : require('./power_word_stun.jpg'),
  "Prayer of Healing"            : require('./prayer_of_healing.jpg'),
  "Prestidigitation"             : require('./prestidigitation.jpg'),
  "Prismatic Spray"              : require('./prismatic_spray.jpg'),
  "Prismatic Wall"               : require('./prismatic_wall.jpg'),
  "Private Sanctum"              : require('./private_sanctum.jpg'),
  "Produce Flame"                : require('./produce_flame.jpg'),
  "Programmed Illusion"          : require('./programmed_illusion.jpg'),
  "Project Image"                : require('./project_image.jpg'),
  "Protection From Energy"       : require('./protection_from_energy.jpg'),
  "Protection from Evil and Good": require('./protection_from_evil_and_good.jpg'),
  "Protection from Poison"       : require('./protection_from_poison.jpg'),
  "Purify Food and Drink"        : require('./purify_food_and_drink.jpg'),
  "Raise Dead"                   : require('./raise_dead.jpg'),
  "Ray of Enfeeblement"          : require('./ray_of_enfeeblement.jpg'),
  "Ray of Frost"                 : require('./ray_of_frost.jpg'),
  "Regenerate"                   : require('./regenerate.jpg'),
  "Reincarnate"                  : require('./reincarnate.jpg'),
  "Remove Curse"                 : require('./remove_curse.jpg'),
  "Resilient Sphere"             : require('./resilient_sphere.jpg'),
  "Resistance"                   : require('./resistance.jpg'),
  "Resurrection"                 : require('./resurrection.jpg'),
  "Reverse Gravity"              : require('./reverse_gravity.jpg'),
  "Revivify"                     : require('./revivify.jpg'),
  "Rope Trick"                   : require('./rope_trick.jpg'),
  "Sacred Flame"                 : require('./sacred_flame.jpg'),
  "Sanctuary"                    : require('./sanctuary.jpg'),
  "Scorching Ray"                : require('./scorching_ray.jpg'),
  "Scrying"                      : require('./scrying.jpg'),
  "Secret Chest"                 : require('./secret_chest.jpg'),
  "See Invisibility"             : require('./see_invisibility.jpg'),
  "Seeming"                      : require('./seeming.jpg'),
  "Sending"                      : require('./sending.jpg'),
  "Sequester"                    : require('./sequester.jpg'),
  "Shapechange"                  : require('./shapechange.jpg'),
  "Shatter"                      : require('./shatter.jpg'),
  "Shield"                       : require('./shield.jpg'),
  "Shield of Faith"              : require('./shield_of_faith.jpg'),
  "Shillelagh"                   : require('./shillelagh.jpg'),
  "Shocking Grasp"               : require('./shocking_grasp.jpg'),
  "Silence"                      : require('./silence.jpg'),
  "Silent Image"                 : require('./silent_image.jpg'),
  "Simulacrum"                   : require('./simulacrum.jpg'),
  "Sleep"                        : require('./sleep.jpg'),
  "Sleet Storm"                  : require('./sleet_storm.jpg'),
  "Slow"                         : require('./slow.jpg'),
  "Spare the Dying"              : require('./spare_the_dying.jpg'),
  "Speak with Animals"           : require('./speak_with_animals.jpg'),
  "Speak with Dead"              : require('./speak_with_dead.jpg'),
  "Speak with Plants"            : require('./speak_with_plants.jpg'),
  "Spider Climb"                 : require('./spider_climb.jpg'),
  "Spike Growth"                 : require('./spike_growth.jpg'),
  "Spirit Guardians"             : require('./spirit_guardians.jpg'),
  "Spiritual Weapon"             : require('./spiritual_weapon.jpg'),
  "Stinking Cloud"               : require('./stinking_cloud.jpg'),
  "Stone Shape"                  : require('./stone_shape.jpg'),
  "Stoneskin"                    : require('./stoneskin.jpg'),
  "Storm of Vengeance"           : require('./storm_of_vengeance.jpg'),
  "Suggestion"                   : require('./suggestion.jpg'),
  "Sunbeam"                      : require('./sunbeam.jpg'),
  "Sunburst"                     : require('./sunburst.jpg'),
  "Symbol"                       : require('./symbol.jpg'),
  "Telekinesis"                  : require('./telekinesis.jpg'),
  "Telepathic Bond"              : require('./telepathic_bond.jpg'),
  "Teleport"                     : require('./teleport.jpg'),
  "Teleportation Circle"         : require('./teleportation_circle.jpg'),
  "Thaumaturgy"                  : require('./thaumaturgy.jpg'),
  "Thunderwave"                  : require('./thunderwave.jpg'),
  "Time Stop"                    : require('./time_stop.jpg'),
  "Tiny Hut"                     : require('./tiny_hut.jpg'),
  "Tongues"                      : require('./tongues.jpg'),
  "Transport via Plants"         : require('./transport_via_plants.jpg'),
  "Tree Stride"                  : require('./tree_stride.jpg'),
  "True Polymorph"               : require('./true_polymorph.jpg'),
  "True Resurrection"            : require('./true_resurrection.jpg'),
  "True Seeing"                  : require('./true_seeing.jpg'),
  "True Strike"                  : require('./true_strike.jpg'),
  "Unseen Servant"               : require('./unseen_servant.jpg'),
  "Vampiric Touch"               : require('./vampiric_touch.jpg'),
  "Vicious Mockery"              : require('./vicious_mockery.jpg'),
  "Wall of Fire"                 : require('./wall_of_fire.jpg'),
  "Wall of Force"                : require('./wall_of_force.jpg'),
  "Wall of Ice"                  : require('./wall_of_ice.jpg'),
  "Wall of Stone"                : require('./wall_of_stone.jpg'),
  "Wall of Thorns"               : require('./wall_of_thorns.jpg'),
  "Warding Bond"                 : require('./warding_bond.jpg'),
  "Water Breathing"              : require('./water_breathing.jpg'),
  "Water Walk"                   : require('./water_walk.jpg'),
  "Web"                          : require('./web.jpg'),
  "Weird"                        : require('./weird.jpg'),
  "Wind Walk"                    : require('./wind_walk.jpg'),
  "Wind Wall"                    : require('./wind_wall.jpg'),
  "Wish"                         : require('./wish.jpg'),
  "Word of Recall"               : require('./word_of_recall.jpg'),
  "Zone of Truth"                : require('./zone_of_truth.jpg'),
};

export default spellImages;
